# Feed update interval in minutes
update_interval: 60
# The time to sleep between send requests when broadcasting a new feed entry.
# Set to 0 to disable sleep or -1 to run all requests asynchronously at once.
spam_sleep: 2
# The prefix for all commands
# It has to be prefixed with ! in matrix to be recognised
command_prefix: "rss"
# Send Messages as TEXT or NOTICE
message_type: "NOTICE"
# Users who can bypass room permission checks
admins:
- "@user:example.com"
